# This workflow runs for every pull request to lint and test the proposed changes.

name: Check

on:
    pull_request:

jobs:
    # NPM install is done in a separate job and cached to speed up the following jobs.
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [15, 16]

        steps:
            -
                uses: actions/checkout@v2
            -
                name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -
                name: Install playwright deps
                run : npx playwright install-deps
            -
                name: Install Dependencies
                run: npm install
            -
                name: Cache Node Modules
                if: ${{ matrix.node-version == 16 }}
                uses: actions/cache@v2
                with:
                path: |
                    node_modules
                key: cache-${{ github.run_id }}-v16
             -
                name: Run Windows or MacOs tests
                run: npm test
                if: ${{ matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}
            -
                name: Run Linux tests
                run: xvfb-run --auto-servernum -- npm test
                if: ${{ matrix.os == 'ubuntu-latest'}}

    lint:
        name: Lint
        needs: [build_and_test]
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
            -
                name: Use Node.js 16
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -
                name: Load Cache
                uses: actions/cache@v2
                with:
                    path: |
                        node_modules
                    key: cache-${{ github.run_id }}-v16
            -
                run: npm run lint
